### PR TITLE
Issue #1 - Add Code of Conduct

### LINKED ISSUE #1: Add Code of Conduct

### PR DESCRIPTION
**Pull request by MJJoyce**
Resolve #1

### CODE REVIEW

**Comment by MJJoyce** [comment]
Note:
- This is one of the "default" code of conduct files that GitHub provides. Not sure if this covers everything we're looking for or not.
- I put `pds_operator@jpl.nasa.gov` as the contact email. It would probably be better to change this to a specific email for handling code of conduct sort of communications I'm just not sure what that email would be. I imagine it might be intimidating if someone wants to send a concern and it looks like the email is going to go to a project wide mailing list.

**Comment by nutjob4life** [comment]
Hi @MJJoyce! And @jordanpadams and @tloubrieu-jpl! (Adding you as reviewers on this PR.)

I think I mentioned during another stand-up meeting that I wrote our own PDS [code of conduct](https://github.com/NASA-PDS/pds-template-repo-java/blob/main/.github/code_of_conduct.md) and [contributors' guide](https://github.com/NASA-PDS/pds-template-repo-java/blob/main/.github/contributing.md) available in the PDS Java repo. This was before the generic `.github` repo.

Were these "no good"? 😅

**Comment by MJJoyce** [comment]
Oh good lord I didn't even realize those were a thing! I probably failed to listen properly. Sorry!!!!

I'll work on updating these to what you already created!

**Comment by jordanpadams** [comment]
[Review from JPL/Caltech SRA here](https://github.com/NASA-PDS/.github/issues/1#issuecomment-900497433)

**Comment by MJJoyce** [comment]
Updated with @nutjob4life's files!

**Comment by nutjob4life** [comment]
Looks great to me 🤪 but I might be biased!

**Review by nutjob4life — APPROVED** [review]

**Review by jordanpadams — APPROVED** [review]

**Pull request merged**
